# Tên của workflow này, sẽ hiển thị trong tab 'Actions' của GitHub.
name: Deploy to GitHub Pages

# Kích hoạt workflow khi có sự kiện push (đẩy code) lên nhánh 'main'.
# Hoặc thay 'main' bằng 'master' nếu đó là nhánh chính của bạn.
on:
  push:
    branches:
      - main # Thay thế bằng tên nhánh chính của bạn nếu khác (ví dụ: master)

# Các công việc (jobs) mà workflow này sẽ thực hiện.
jobs:
  # Định nghĩa một job có tên 'build-and-deploy'.
  build-and-deploy:
    # Chạy job này trên hệ điều hành Ubuntu mới nhất.
    runs-on: ubuntu-latest

    # Các bước (steps) trong job này.
    steps:
      # Bước 1: Checkout mã nguồn từ repository.
      # Đây là một action tiêu chuẩn để lấy code của bạn về môi trường GitHub Actions.
      - name: Checkout 
        uses: actions/checkout@v3

      # Bước 2: Cấu hình GitHub Pages.
      # Bước này thiết lập môi trường để triển khai GitHub Pages.
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Bước 3: Tải Artifact lên GitHub Pages.
      # Artifact là các file mà bạn muốn triển khai (trong trường hợp này là index.html).
      # 'path: .' có nghĩa là tải tất cả các file trong thư mục gốc của repository.
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.' # Đường dẫn tới thư mục chứa các file web tĩnh (index.html, css, js). Ở đây là thư mục gốc.

      # Bước 4: Triển khai lên GitHub Pages.
      # Đây là bước cuối cùng để đưa trang web của bạn lên trực tuyến.
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
