# Tên của workflow này, sẽ hiển thị trong tab 'Actions' của GitHub.
name: Deploy to GitHub Pages

# Kích hoạt workflow khi có sự kiện push (đẩy code) lên nhánh 'master'.
on:
  push:
    branches:
      - master # Đảm bảo đây là nhánh chính của bạn

# Các công việc (jobs) mà workflow này sẽ thực hiện.
jobs:
  # Định nghĩa một job có tên 'build-and-deploy'.
  build-and-deploy:
    # Chạy job này trên hệ điều hành Ubuntu mới nhất.
    runs-on: ubuntu-latest

    # Các bước (steps) trong job này.
    steps:
      # Bước 1: Checkout mã nguồn từ repository. Đã cập nhật lên v4.
      - name: Checkout
        uses: actions/checkout@v4

      # Bước 2: Cấu hình GitHub Pages. Đã cập nhật lên v3.
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Bước 3: Tải Artifact lên GitHub Pages. Đã cập nhật lên v3 (phiên bản mới nhất được khuyến nghị).
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Đường dẫn tới thư mục chứa các file web tĩnh (index.html, css, js). Ở đây là thư mục gốc.

      # Bước 4: Triển khai lên GitHub Pages. Đã cập nhật lên v3.
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
